spring.application.name: dynamodb

#################### Server Configuration ####################
server:
  port: 8090
  servlet.context-path: /dynamodb-1.0
  tomcat:
    accept-count: 100
    threads:
      min-spare: 10
      max: 200

#################### AWS Configuration ####################
amazon:
  aws:
    accesskey: <aws-iam-access-key>
    secretkey: <aws-iam-secret-key>
    region: <aws-dynamodb-region>
  dynamodb:
    endpoint: dynamodb.<aws-dynamodb-region>.amazonaws.com
    connection:
      maxsize: 100
      timeout: 5000
      socket:
        timeout: 5000

